CREATE TABLE IF NOT EXISTS "epicrisis_clinical_data" (
	"epicrisis_id" integer PRIMARY KEY NOT NULL,
	"cirugia_previas" boolean,
	"cirugias_previas_cantidad" integer,
	"farmacos" text,
	"vmi" boolean,
	"vmi_evidencia" text,
	"vmi_motivo" text,
	"vmi_urgente" boolean,
	"vmi_prono" boolean,
	"vmi_comments" text,
	"maniobras_reanimacion" text,
	"ciclos_paro" integer,
	"cantidad_paros" integer,
	"transfusion" boolean,
	"transfusion_evidencia" text,
	"transfusion_unidades" integer,
	"transfusion_comments" text,
	"drogas_vasoactivas" boolean,
	"drogas_vasoactivas_evidencia" text,
	"drogas_vasoactivas_multiples" boolean,
	"drogas_vasoactivas_comments" text,
	"cirugias_hosp" integer,
	"cirugias_hosp_descripcion" text,
	"infeccion_urinario" boolean,
	"infeccion_urinario_evidencia" text,
	"infeccion_urinario_germen" text,
	"infeccion_urinario_comments" text,
	"infeccion_respiratorio" boolean,
	"infeccion_respiratorio_evidencia" text,
	"infeccion_respiratorio_germen" text,
	"infeccion_respiratorio_comments" text,
	"infeccion_vascular" boolean,
	"infeccion_vascular_evidencia" text,
	"infeccion_vascular_germen" text,
	"infeccion_vascular_comments" text,
	"infeccion_sangre" boolean,
	"infeccion_sangre_evidencia" text,
	"infeccion_sangre_germen" text,
	"infeccion_sangre_comments" text,
	"infeccion_cerebral" boolean,
	"infeccion_cerebral_evidencia" text,
	"infeccion_cerebral_germen" text,
	"infeccion_cerebral_comments" text,
	"infeccion_cardiaco" boolean,
	"infeccion_cardiaco_evidencia" text,
	"infeccion_cardiaco_germen" text,
	"infeccion_cardiaco_comments" text,
	"infeccion_quirurgico" boolean,
	"infeccion_quirurgico_evidencia" text,
	"infeccion_quirurgico_germen" text,
	"infeccion_quirurgico_comments" text,
	"infeccion_gastrointestinal" boolean,
	"infeccion_gastrointestinal_evidencia" text,
	"infeccion_gastrointestinal_germen" text,
	"infeccion_gastrointestinal_comments" text,
	"infeccion_piel_tejidos" boolean,
	"infeccion_piel_tejidos_evidencia" text,
	"infeccion_piel_tejidos_germen" text,
	"infeccion_piel_tejidos_comments" text,
	"trr" boolean,
	"trr_evidencia" text,
	"trr_tipo" text,
	"trr_comments" text,
	"falla_renal" boolean,
	"falla_renal_evidencia" text,
	"falla_renal_comments" text,
	"falla_nervioso" boolean,
	"falla_nervioso_evidencia" text,
	"falla_nervioso_comments" text,
	"falla_vascular" boolean,
	"falla_vascular_evidencia" text,
	"falla_vascular_comments" text,
	"falla_cardiaco" boolean,
	"falla_cardiaco_evidencia" text,
	"falla_cardiaco_comments" text,
	"falla_pulmonar" boolean,
	"falla_pulmonar_evidencia" text,
	"falla_pulmonar_comments" text,
	"falla_hepatico" boolean,
	"falla_hepatico_evidencia" text,
	"falla_hepatico_comments" text,
	"falla_otra" boolean,
	"falla_otra_evidencia" text,
	"falla_otra_descripcion" text,
	"falla_otra_comments" text,
	"diagnostico_ingreso" text,
	"diagnostico_egreso" text,
	"farmacos_hosp" text,
	"mortalidad" boolean,
	"mortalidad_evidencia" text,
	"mortalidad_comments" text,
	"hfav" boolean,
	"hfav_evidencia" text,
	"hfav_comments" text
);
--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "tipo_prevision" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "quintil_teorico" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "concordancia_gse" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "fecha_ingreso_hosp" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "fecha_egreso_hosp" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "fecha_ingreso_uci" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "fecha_egreso_uci" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "comentario_final" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "pdf_path" text;--> statement-breakpoint
ALTER TABLE "epicrisis" ADD COLUMN "pdf_data" "bytea";--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "epicrisis_clinical_data" ADD CONSTRAINT "epicrisis_clinical_data_epicrisis_id_epicrisis_id_fk" FOREIGN KEY ("epicrisis_id") REFERENCES "public"."epicrisis"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
