<script setup lang="ts">
import { computed, ref, watch, nextTick } from 'vue'
import { normalizeSearch } from '@/constants/clinicalItems'

const props = defineProps<{
  layoutData: any
  searchQuery?: string
}>()

const pages = computed(() => {
  if (Array.isArray(props.layoutData)) return props.layoutData
  if (props.layoutData?.pages) return props.layoutData.pages
  // If it's a single page wrapped
  if (props.layoutData?.html) return [props.layoutData]
  return []
})

const containerRef = ref<HTMLDivElement | null>(null)

// HU-046: búsqueda dentro del layout. Misma interfaz que PdfViewer (matchCount /
// scrollToMatch) para que AnnotationView no tenga que saber cuál visor está montado.
const matchCount = ref(0)

function applyHighlights() {
  if (!containerRef.value) return
  const spans = containerRef.value.querySelectorAll<HTMLElement>('.pdf-span')
  const q = normalizeSearch(props.searchQuery?.trim() ?? '')
  let count = 0
  spans.forEach((span) => {
    const matches = q.length >= 2 && normalizeSearch(span.textContent ?? '').includes(q)
    span.classList.toggle('search-highlight', matches)
    // La activa se recalcula desde cero en cada búsqueda: si no se limpiara aquí,
    // el naranjo de la consulta anterior quedaría pegado para siempre.
    span.classList.remove('search-highlight-active')
    if (matches) count++
  })
  matchCount.value = count
}

function scrollToMatch(index: number) {
  if (!containerRef.value) return
  const matches = containerRef.value.querySelectorAll<HTMLElement>('.search-highlight')
  matches.forEach((el, i) => el.classList.toggle('search-highlight-active', i === index))
  matches[index]?.scrollIntoView({ behavior: 'smooth', block: 'center' })
}

// El HTML del layout llega por v-html, así que hay que reaplicar cuando cambia
// el documento y no solo cuando cambia la consulta.
watch(() => props.searchQuery, applyHighlights)
watch(pages, () => nextTick(applyHighlights), { immediate: true })

defineExpose({ containerRef, matchCount, scrollToMatch })
</script>

<template>
  <div
    ref="containerRef"
    class="flex flex-col flex-1 min-h-0 bg-[#4a4a4a] overflow-y-auto py-6 px-4 items-center pdf-document-container text-selection-zone"
  >
    <!-- Render the exact HTML generated by the python script -->
    <div
      v-for="(page, pIdx) in pages"
      :key="pIdx"
      v-html="page.html"
    ></div>
  </div>
</template>

<style>
/* Estilos globales para la compatibilidad con PDF.js/useTextSelection */
.pdf-span {
  user-select: text;
  -webkit-user-select: text;
}
.pdf-span::selection {
  background: rgba(0, 120, 255, 0.25);
}

/* HU-046: resaltado de búsqueda — mismos colores que el fallback PdfViewer */
.pdf-document-container .search-highlight {
  background-color: rgba(250, 200, 0, 0.5);
  border-radius: 2px;
  outline: 1px solid rgba(200, 150, 0, 0.5);
}
.pdf-document-container .search-highlight.search-highlight-active {
  background-color: rgba(255, 140, 0, 0.65);
  outline: 1px solid rgba(200, 90, 0, 0.8);
}
</style>
